### ISSUE TITLE
Different sign for placebo coefficient with dyn and stat (Stata)

### ISSUE THREAD

**Issue by Gilles-Spielvogel** [chaisemartinPackages/did_multiplegt#26]
Hello,

Many thanks for the library and the recent updates!

I have estimated (almost) the same model on the same data (continuous outcome, binary treatment, two periods) using the dyn and stat modes.
I find as expected (almost) the same results for the DID estimator, but not for the placebo regression. In fact, the absolute value of the placebo coefficient is the same, but the sign is reversed. 
I find this puzzling and I thought this was an issue worth raising with you.

My models and results look like this:

`did_multiplegt (stat) Y G T D, estimator( as) cluster(G) switchers(up)  exact_match  placebo(1) graph_off`

|           | Estimate | SE       | LB CI     | UB CI    | Switchers | Stayers |
|-----------|----------|----------|-----------|----------|-----------|---------|
| AS        | 4.213364 | .8534473 | 2.540607  | 5.88612  | 500       | 11786   |
| Placebo_1 | -.892202 | .7020076 | -2.268137 | .4837329 | 474       | 5656    |
 
`did_multiplegt (dyn) Y G T D,  cluster(G) switchers(in) only_never_switchers placebo(1) graph_off `

|           | Estimate | SE       | LB CI     | UB CI    | N     | Switchers |
|-----------|----------|----------|-----------|----------|-------|-----------|
| Effect_1  | 4.249127 | .7965185 | 2.687979  | 5.810274 | 11811 | 499       |
| Placebo_1 | .8922021 | .7030345 | -.4857202 | 2.270124 | 6130  | 474       |

Many thanks if you can help me understand this!

Best,

Gilles

**Comment by chaisemartinPackages** [comment]
Dear Gilles,

Thank you Gilles for this test, this is all the more reassuring !

This derives from different conventions across packages. In [de Chaisemartin et D’Haultfœuille 2024](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3731856), placebos are constructed by taking differences that go in the past (see section 3.5) compared to the first treatment period. On the contrary in [de Chaisemartin et al. 2024](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4011782), placebos are forward differences before the period of the change. 

This explains why the coefficients can be similar but of opposite signs.

Hope this helps,
Romain
